# Main configuration file for gy≈çza

project:
    # Specify the design of your experiment: codon | provided | barcode | random
    # codon: Automatically generate all expected mutants based on the codon mode
    # provided: You provide the list of expected mutants
    # barcode: You provide the dataframe of barcode-variant associations
    # random: Random mutagenesis - mutants observed in the sequencing data are directly annotated
    design: 'codon'
    # Specify path to folder containing project-specific files
    folder: '/home/rodur28/fks_gyoza/config/project_files/'
    # Specify what makes each sample unique (other than Timepoint and Replicate)
    sample_attributes: ['strain','paralog','hotspot','Mutated_seq']
    # Specify what makes each screening condition unique
    # (other than Timepoint)
    screening_attributes: ['compound']

reads:
    # Specify if reads are paired-end (True) or single-end (False)
    paired: False
    # Specify path to directory containing sequencing data
    path: '/home/rodur28/novaseq_run2/reads/sra_reads/'
    # Specify targeted read count per sample in scientific notation
    exp_rc_per_sample: 7e4
    # Specify read count threshold (integer) to label variants with a confidence score
    rc_threshold: 10

barcode:
    # For 'barcode' designs only
    # Specify barcode attributes to label each variant, e.g. ['bc_index'] (default: [])
    attributes: []

random:
    # For 'random' designs only
    # Acceptable number of amino acid changes relative to wild-type
    Nham_aa_max: 1

process_all_samples: False
    # Set to True to override sample selection specified in the Analyze/Report columns of the layout
    # This will include all samples from the layout for both processing and reporting

perform_qc: True
    # Set to True if you want to run Fastp on all raw FASTQ files and generate a MultiQC report

process_frequencies: True
    # Set to True if you want to convert allele frequencies into functional impact scores
    # Set to False to analyze unscreened libraries or output samples with no matching input replicate

normalize_with_gen: True
    # Set to True if you want to normalize impact scores with the number of cellular generations

plot_formats: ['png']
    # Indicate in which format(s) you want to export plots, e.g. ['png','pdf'] (most formats supported)
    # Plots will be exported in .svg regardless of what is specified